<img src='tensor.png'>

<img src='parcs.png'>

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

2022-06-30 09:42:52.551779: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-30 09:42:52.551813: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [9]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [10]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

2022-06-30 09:47:31.137827: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-06-30 09:47:31.137878: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-30 09:47:31.137925: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (toshiba): /proc/driver/nvidia/version does not exist


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [12]:
model.fit(train_images, train_labels, epochs=5)

2022-06-30 09:47:33.476665: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/5
1875/1875 [==============================] - 10s 4ms/step - loss: 0.4965 - accuracy: 0.8274
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3731 - accuracy: 0.8655
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3366 - accuracy: 0.8775
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.3110 - accuracy: 0.8862
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2945 - accuracy: 0.8906


In [13]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

2022-06-30 09:48:18.214986: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 31360000 exceeds 10% of free system memory.


313/313 [==============================] - 1s 3ms/step - loss: 0.3418 - accuracy: 0.8771
Test accuracy: 0.8770999908447266


In [14]:
predictions = model.predict(test_images)

  1/313 [..............................] - ETA: 34s

2022-06-30 09:48:19.614130: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 31360000 exceeds 10% of free system memory.


313/313 [==============================] - 1s 3ms/step


In [15]:
predictions[0]

array([1.1353302e-05, 7.2295343e-06, 2.6216746e-06, 1.5697663e-07,
       5.2180678e-07, 2.1131696e-02, 4.2595657e-05, 3.9985795e-02,
       7.0612409e-06, 9.3881088e-01], dtype=float32)

In [16]:
np.argmax(predictions[0])

9

In [17]:
test_labels[0]

9

In [18]:
img = test_images[0]

print(img.shape)

(28, 28)


In [19]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [20]:
predictions_single = model.predict(img)

print(predictions_single)

1/1 [==============================] - 0s 40ms/step
[[1.1353315e-05 7.2295356e-06 2.6216751e-06 1.5697680e-07 5.2180690e-07
  2.1131685e-02 4.2595624e-05 3.9985802e-02 7.0612418e-06 9.3881106e-01]]


In [21]:
np.argmax(predictions_single[0])

9